### ISSUE TITLE
Linked DOCX file is missing

### ISSUE THREAD

**Issue by miriam-orion** [rmraya/Fluenta#11]
I use the Fluenta Addon in OxygenXML. A DOCX file, that is linked inside a topic, is not included during export/import. It is linked like this: `<xref href="some_folder/some_file.docx" format="docx"/>`
Is there an option to include files that are linked with @xref? (for DOCX, ZIP, 7z, PDF, ...)

**Comment by rmraya** [comment]
Fluenta depends on the value of the `@format` attribute. If the value is `null`, `dita` or `ditamap`, the referenced material is processed. Linked content is ignored otherwise.

It is possible to modify the code and extract text from files supported by [OpenXLIFF Filters](https://github.com/rmraya/OpenXLIFF), the library used for generating XLIFF. That library already includes support for .docx files.

This is the source code repository for the real [Fluenta](https://www.maxprograms.com/products/fluenta.html). Oxygen's add-on is based on a very old version of this tool. 

Try the real version of Fluenta from [Maxprograms](https://maxprograms.com) and if you like it, request support for linked Word files to tech@maxprograms.com
